# Generated by Django 5.0.3 on 2024-03-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255, verbose_name='Category name')),
                ('cat_desc', models.CharField(max_length=255, verbose_name='Category description')),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['id'],
            },
        ),
    ]
