# Generated by Django 5.0.3 on 2024-03-17 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_news.category', verbose_name=''),
        ),
        migrations.AddField(
            model_name='news',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Views count'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Category description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Category name'),
        ),
    ]
